# Generated by Django 6.0.2 on 2026-07-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_tags_product_tags"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tags",
            new_name="Tag",
        ),
    ]
